# simple report on admission

## data
Following data is collected from 2001 until 2020.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
pd.read_excel('rejection_rate.xlsx')

   semester  batches  applied  accepted  rejection
0    2001_1        1        5         4       0.20
1    2002_1        2       10         3       0.70
2    2003_1        2       15         7       0.53
3    2004_1        2       20         6       0.70
4    2005_1        3       25        12       0.52
5    2006_1        2       20         7       0.65
6    2006_2        2       10         2       0.80
7    2007_1        3       25         9       0.64
8    2007_2        2       15         1       0.93
9    2008_1        3       25        11       0.56
10   2008_2        3       20         4       0.80
11   2009_1        3       30        14       0.53
12   2009_2        3       25         6       0.76
13   2010_1        3       35        13       0.63
14   2010_2        3       25         9       0.64
15   2011_1        3       40        14       0.65
16   2011_2        3       20         6       0.70
17   2012_1        3       45        20       0.56
18   2012_2        2       10         2       0.80
19   2013_1        4       55        27       0.51
20   2013_2        2       15         4       0.73
21   2014_1        4       60        17       0.72
22   2014_2        2       20         9       0.55
23   2015_1        4       45        16       0.64
24   2015_2        2       10         4       0.60
25   2016_1        4       40        13       0.68
26   2016_2        1        5         4       0.20
27   2017_1        4       25         9       0.64
28   2017_2        1       10         3       0.70
29   2018_1        3       25        15       0.40
30   2018_2        2       20         6       0.70
31   2019_1        3       35        14       0.60
32   2019_2        3       25         6       0.76
33   2020_1        2       25         4       0.84
34   2020_2        4       45        14       0.69

## admission
It start at 2001 only in first semester until 2005. From 2006 there are two addmission in a year, in the first and second semesters. Data for number of batches, total applicants and accepted applicants are given in previous table.

## rejection rate
Rejection rate (RR) is defined as

$$\tag{1}
{\rm RR} = \frac{\rm accepted \ applicants}{\rm total \ applicants}.
$$

Equation (1) can be multiplied with 100 to get the result in percentage.

 In order to get insight during 2001 - 2020 following are RR for every semester

 ![](rejection_rate_semester.png)

 The lowest RR is 0.2 and it occurs on 2001_1 and 2016_1 semesters. And the highest is about 0.9 and it happes on 2007_2 semester.

## batches
To accommodate more applicants several batches are offered in each semester.

![](number_of_batches_semester.png)

Number of batches varies from 1 to 4 for each semester as shown above.

# batches and rr
Higher rejection rate RR tells us the only few applicants are accepted. Does it has relation with number of batches?

![](rejection_rate_number_of_batches.png)

Above figures shows that only one semester with one batch gives about 0.7 rejection rate (or 70%), the other semesters requires at least 2 semester to get rejection rate above 0.5 (or 50%).

## another relation
From available data relation between number of batches, total applicants, and rejection rate can be obtained as follow.

![](number_of_batches_applied_rejection.png)

Horizontal axis is showing total applicants that applied in certain semester and vertical axis is showing number of batches of related semester. The markers give additional dimension using color and size, which relates to rejection rate. Smaller size and more blue colored indicates lower rejection rate, while larger size and more red colored indicates higher rejection rate.

Some findings
- number of batches equal to one can give lower or higher rejection rate.
- the highest rejection rate is when number of batches about 2-3, but not 4.
- the highest number of batches, value is 4, does not produce highest rejection rate.

## summaries
Following can be summerized from data collected between 2001-2020
- Total applicants every semester more than 25 requires up to 4 bathes but this not give the highest rejection rate.
- Number of baches for every semester should be between 2 and 3, it will give optimum rejection rate.
- Influence of rejection rate should be further investigated in its relation to minimum study duration and students grade.

## appendix
Commands to do the conversion
+ Notebook (ipynb) to LaTeX (tex)
+ LaTeX (tex) to PDF (pdf)

In [2]:
!jupyter nbconvert simple_report_on_admission.ipynb --to latex

[NbConvertApp] Converting notebook simple_report_on_admission.ipynb to latex
[NbConvertApp] Writing 26171 bytes to simple_report_on_admission.tex

In [3]:
!xelatex simple_report_on_admission.tex -quiet

[simple_report_on_admission.pdf](simple_report_on_admission.pdf)